version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - run:
          name: dependencies
          command: pip install -r requirements.txt
      - run:
          name: validate
          command: ./validate.py
